application:
  protocol: http
  host: 127.0.0.1
  base_url: "http://nftminting.com:8080"

debug: true

frontend_url: "http://nftminting.com:3000"

secret:
  token_expiration: 15
  cookie_expiration: 1440
